names:
- First Name
- Last Name
picture:
  path: /assets/images/profile.png
contact:
  entries:
    phoneNumber:
      url: "tel:+000000000"
      newInstance: false
      icon:
        path: /assets/icons/phone.svg
    emailAddress:
      url: "mailto:contact@eghggggggggggggxample.com"
      newInstance: false
      icon:
        path: /assets/icons/envelope.svg
aspects:
  technologies:
    entries:
      example:
        path: https://example.com/
        icon:
          path: /icons/example.svg
  communication:
    entries:
      lithuanian:
        icon:
          path: /icons/lithuania.svg
      english:
        icon:
          path: /icons/united-kingdom.svg
timelines:
  experience:
    entries:
      example:
        timespan:
          from: 2023-09-03
          to: 2024-09-03
  education:
    entries:
      example:
        timespan:
          from: 2024-09-03